-- MySQL Script generated by MySQL Workbench
-- Sat Nov 23 14:32:32 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema u0826441_allmark
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `u0826441_allmark` ;

-- -----------------------------------------------------
-- Schema u0826441_allmark
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `u0826441_allmark` DEFAULT CHARACTER SET utf8 ;
USE `u0826441_allmark` ;

-- -----------------------------------------------------
-- Table `u0826441_allmark`.`attribute`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `u0826441_allmark`.`attribute` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `attr_id` INT(11) NOT NULL,
  `attr_value` VARCHAR(255) NOT NULL,
  `product_id` INT(11) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_attribute_product_idx` (`product_id` ASC),
  CONSTRAINT `fk_attribute_product`
    FOREIGN KEY (`product_id`)
    REFERENCES `u0826441_allmark`.`product` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `u0826441_allmark`.`category`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `u0826441_allmark`.`category` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `cat_id` INT(11) NOT NULL,
  `product_id` INT(11) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_category_product_idx` (`product_id` ASC),
  CONSTRAINT `fk_category_product`
    FOREIGN KEY (`product_id`)
    REFERENCES `u0826441_allmark`.`product` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `u0826441_allmark`.`customer`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `u0826441_allmark`.`customer` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `email` VARCHAR(255) NULL,
  `password` VARCHAR(255) NULL,
  `email_confirmed` TINYINT(1) NOT NULL DEFAULT 0,
  `national_catalog_apikey` VARCHAR(255) NULL,
  `guid` VARCHAR(255) NULL,
  `name` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `u0826441_allmark`.`product`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `u0826441_allmark`.`product` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `good_id` INT(11) NULL,
  `gtin` INT(14) NULL,
  `good_name` VARCHAR(255) NULL,
  `tnved` VARCHAR(10) NULL,
  `brand_id` INT(11) NULL,
  `customer_id` INT(11) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_product_customer_idx` (`customer_id` ASC),
  CONSTRAINT `fk_product_customer`
    FOREIGN KEY (`customer_id`)
    REFERENCES `u0826441_allmark`.`customer` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
